### PR TITLE
✨Major Release: Netlify CMS Implementation ✨

### PR DESCRIPTION
**Pull request by abcalderon3**
We've finally got Netlify CMS integrated with the site.

With this implementation, content creators can create content through Netlify CMS by going to https://ffxivpocketguide.com/admin/ .

I've made a few updates to the front-end to be compatible with the new schema, which we've standardized across all instance types.

### CODE REVIEW

**Comment by joshdrink** [comment]
Okay, so one core issue:
- when editing a pre-existing guide, I'm getting an error (attached)

Other thoughts:
- it would be handy if we could better control the Netlify UI to paginate the steps in the guide creation, but I can't seem to find anything in their docs about separating fields into sections or pages...
- otherwise this looks really solid - I generally prefer this to Forestry, so it's a great improvement
- we might want to add more context to the field guide and in the form of paragraph text or longer labels to explain the purposes of each field that isn't self explanatory to avoid other editors from becoming confused

**Comment by abcalderon3** [comment]
@joshdrink , thanks for taking look! Responding to your feedback inline below...

> Okay, so one core issue:
> 
> * when editing a pre-existing guide, I'm getting an error (attached)

Oh, this is likely due to the changes to the front-matter schema (which Netlify is expecting to read/write), in order to standardize across various instance types. Our focus was primarily on implementation for new content, going forward, and ensuring the front-end would be cross-compatible, not necessarily with Netlify.

We could totally address this by converting the front-matter of the old guides to the new schema. How critical would you see that for this release? IMO, I would rather separate those concerns into their own chunks of work, in order to 1) reduce the surface area of this update (which is large as it is) and 2) unblock new Shadowbringers content creation sooner.

Additionally, I would love to have a few front-end automated tests implemented before doing such a large data transformation, and that'd also be a good point at which we decide to stick with front-matter or switch to JSON.

> 
> Other thoughts:
> 
> * it would be handy if we could better control the Netlify UI to paginate the steps in the guide creation, but I can't seem to find anything in their docs about separating fields into sections or pages...

Yea, I agree! The main way I've seen for us to do so would be to implement Custom Widgets. I'm thinking we'll have several ideas for custom improvements to the Netlify UI, so we might want to start a list and then prioritize?

> * otherwise this looks really solid - I generally prefer this to Forestry, so it's a great improvement
> * we might want to add more context to the field guide and in the form of paragraph text or longer labels to explain the purposes of each field that isn't self explanatory to avoid other editors from becoming confused

Totally! Did you see any that could use clarification for this release? Perhaps we could ask our new member to go through the Field Dictionary with that lens as a new pair of eyes?

**Comment by joshdrink** [comment]
@abcalderon3 Okay, so!

I don't think we need to migrate old guides over yet, no, however it was a little confusing for them to appear in the list of editable guides. I wonder if we could hide them from Netlify for the time being? Not entirely sure how to go about doing that though.

In terms of the UI, a list improvements is a great idea. No real rush on this, but I'd love to dig deeper into what our options are down the road.

And nope - it's actually tough for me to be the one to clarify the fields because I was the one that chose them, but let's see if other users start asking questions and we can add/change things from there.

Again, fantastic work on this PR. There's one thing I'm gonna double check, and if you can take a peek at whether we can hide the existing guides for me, we can merge this in.

**Comment by abcalderon3** [comment]
@joshdrink, great point about the old guides being confusing. I've implemented a commit to hide them (using a filter on the collections). I deployed and tested this on the Dev repo, in case you want to see it.

Captured issue #175 for later handling.

Let me know if there's anything else you think of before we're all good to merge! 🙏

**Comment by joshdrink** [comment]
Okay, I took a look and I can't remember if we've talked about this previously, but it doesn't look like there's anyway to attach images to attacks right now. In some of the more complicated fights (e.g. A12S) maps/choreography layouts are helpful.

**Comment by abcalderon3** [comment]
Good catch! I added the ability to attach images to attacks.

I noticed in A12S that there are also a few inline images (small icons), in addition to the overall layout maps. Unfortunately, there's not a great immediate solution to provide an ability to include inline images in the Attack Notes. As a workaround, one could include the HTML directly and then separately upload the images into the repo. How important would it be to solve for that use case inside the CMS?

**Comment by joshdrink** [comment]
@abcalderon3 Honestly I don't think it's necessary for us to launch that feature alongside the CMS... It's a pretty edge case, and the guides that generally do require that kind of detail are normally a multi-day endeavour on the author's part, so we can work with the author to make it happen until we find a more elegant solution.

**Pull request merged**
